spring.application.name=bina

#SERVER
server.port=8080

#SPRING
spring.ai.deepseek.api-key=${AI_KEY}
spring.ai.deepseek.chat.options.frequencyPenalty=0.1f
spring.ai.deepseek.chat.options.maxTokens=2048
spring.ai.deepseek.chat.options.presencePenalty=0.1f
spring.ai.deepseek.chat.options.model=deepseek-chat
spring.ai.deepseek.chat.options.temperature=0.98f
spring.ai.deepseek.base-url=https://api.deepseek.com

#PICOVOICE
picovoice.api-key=${PICO_KEY}
picovoice.keyword_file=classpath:config/heybina.ppn

#VOSK
vosk.model-path: models/vosk
assistant:
    enabled: true
    language: ru-RU

#VOICE
app:
    voice:
        auto-start: false  # ????????????? ????????? ??? ?????? ??????????
        sample-rate: 16000
        frame-length: 512
        sensitivity: 0.5   # ???????????????? ???????????